### ISSUE TITLE
container fails to start

### ISSUE THREAD

**Issue by ThyWoof** [michaelgorkow/scs_whisper#2]
Followed instructions step-by-step and got these logs when trying to start the service in SNOW:

exec /usr/local/bin/gunicorn: exec format error
<img width="863" alt="Screenshot 2024-04-09 at 2 20 41 PM" src="https://github.com/michaelgorkow/scs_whisper/assets/13087646/8d347208-59ac-4985-9a4b-53876d9459d7">

any ideas on what I might have miss here.

**Comment by ThyWoof** [comment]
solution: if on a MAC M1/M2, ensure you pass the --platform on build

**Comment by michaelgorkow** [comment]
Thanks for pointing me to this issue. I updated the Readme to include --platform linux/amd64 in the build command.

**Comment by michaelgorkow** [comment]
closed.
